// src/services/analysisApi.ts

export type ResumeSkills = {
  strong: string[];
  listed: string[];
};

type ResumeParseResponse = {
  skills?: ResumeSkills;
};

type GapSkill = {
  skill: string;
  importance: string;
  match_type?: string;
};

type MissingSkill = {
  skill: string;
  importance: string;
  category?: string;
};

type GapAnalysisResponse = {
  match_score: number;
  matched_strong: GapSkill[];
  matched_listed: GapSkill[];
  missing_critical: MissingSkill[];
  missing_preferred: MissingSkill[];
};

// Updated to include the new role_area field generated by the backend
export type JdSkillsResponse = {
  source?: string;
  role_title?: string;
  role_area?: string;
  company?: string;
  required?: string[];
  preferred?: string[];
};

export type AnalyzeResponse = {
  jd_skills: JdSkillsResponse;
  gap_analysis: GapAnalysisResponse;
};

type WindowWithSkillevateConfig = Window & {
  __SKILLEVATE_ANALYSIS_CONFIG__?: {
    apiBaseUrl?: string;
  };
  __SKILLEVATE_GET_ACCESS_TOKEN__?: () => Promise<string>;
};

const DEFAULT_INFERENCE = "rag";

// Added new extraction and direct analysis routes
const API_ROUTES = {
  parseResumeSkills: "/api/resume/skills",
  extractText: "/api/jobs/skills",
  extractPdf: "/api/jobs/skills/file",
  analyzeDirect: "/api/analysis/gap",

  analyzeText: "/api/v1/analyzer/analyze",         // Legacy full pipeline
  analyzePdf: "/api/v1/analyzer/analyze/pdf",      // Legacy full pipeline
};

/** Default when env is unset: local FastAPI on port 8000 (avoids relative URLs hitting the webpack dev server → 404). */
const DEFAULT_ANALYSIS_API_BASE_URL = "http://localhost:8000";

const normalizeBaseUrl = (url: string) => url.trim().replace(/\/+$/, "");

/**
 * Resolves the analysis service base URL.
 *
 * Priority:
 *   1. `window.__SKILLEVATE_ANALYSIS_CONFIG__.apiBaseUrl` — runtime override
 *      (e.g. set from the host shell for E2E tests).
 *   2. `process.env.ANALYSIS_API_BASE_URL` — injected at build time from
 *      `Skillevate-MFE/.env` via webpack `DefinePlugin`.
 *   3. `DEFAULT_ANALYSIS_API_BASE_URL` — local dev fallback (port 8000).
 */
const getRuntimeBaseUrl = (): string => {
  if (typeof window !== "undefined") {
    const runtime = (window as WindowWithSkillevateConfig).__SKILLEVATE_ANALYSIS_CONFIG__;
    if (runtime?.apiBaseUrl?.trim()) {
      return normalizeBaseUrl(runtime.apiBaseUrl);
    }
  }

  const fromEnv =
    typeof process !== "undefined" && typeof process.env?.ANALYSIS_API_BASE_URL === "string"
      ? process.env.ANALYSIS_API_BASE_URL.trim()
      : "";
  if (fromEnv) {
    return normalizeBaseUrl(fromEnv);
  }

  return normalizeBaseUrl(DEFAULT_ANALYSIS_API_BASE_URL);
};

const getAccessToken = async (): Promise<string | null> => {
  if (typeof window === "undefined") return null;

  const tokenProvider = (window as WindowWithSkillevateConfig).__SKILLEVATE_GET_ACCESS_TOKEN__;
  if (!tokenProvider) return null;

  try {
    const token = await tokenProvider();
    return token || null;
  } catch {
    return null;
  }
};

const request = async <T>(path: string, init: RequestInit): Promise<T> => {
  const token = await getAccessToken();
  const headers = new Headers(init.headers ?? undefined);

  if (token) {
    headers.set("Authorization", `Bearer ${token}`);
  }

  const response = await fetch(`${getRuntimeBaseUrl()}${path}`, {
    ...init,
    headers,
  });

  const payloadText = await response.text();
  const parsed = payloadText ? (JSON.parse(payloadText) as unknown) : null;

  if (!response.ok) {
    const detail =
      typeof parsed === "object" &&
      parsed !== null &&
      "detail" in parsed &&
      typeof (parsed as { detail?: unknown }).detail === "string"
        ? (parsed as { detail: string }).detail
        : `Request failed (${response.status})`;
    throw new Error(detail);
  }

  return parsed as T;
};

// ── API Services ─────────────────────────────────────────────────────────────

export const parseResumeSkills = async (file: File): Promise<ResumeSkills> => {
  const formData = new FormData();
  formData.append("file", file);
  formData.append("inference", "ollama");
  formData.append("enrich", "false");

  const response = await request<ResumeParseResponse>(API_ROUTES.parseResumeSkills, {
    method: "POST",
    body: formData,
  });

  if (!response.skills) {
    throw new Error("Resume parser returned no skills.");
  }

  return {
    strong: response.skills.strong ?? [],
    listed: response.skills.listed ?? [],
  };
};

// NEW: Extract skills from pasted JD text or target role string
export const extractJdText = async (jdText: string): Promise<JdSkillsResponse> => {
  return request<JdSkillsResponse>(API_ROUTES.extractText, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      jd_text: jdText,
      inference: DEFAULT_INFERENCE,
    }),
  });
};

// NEW: Extract skills from uploaded JD file
export const extractJdFile = async (file: File): Promise<JdSkillsResponse> => {
  const formData = new FormData();
  formData.append("file", file);
  formData.append("inference", DEFAULT_INFERENCE);

  return request<JdSkillsResponse>(API_ROUTES.extractPdf, {
    method: "POST",
    body: formData,
  });
};

// NEW: Perform gap analysis directly on pre-extracted JSONs (Zero LLM latency)
export const analyzeDirect = async (
  resumeSkills: ResumeSkills,
  jdSkills: JdSkillsResponse
): Promise<AnalyzeResponse> => {
  return request<AnalyzeResponse>(API_ROUTES.analyzeDirect, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      resume_skills: resumeSkills,
      jd_skills: jdSkills,
    }),
  });
};

// ── Legacy Routes (Kept for backward compatibility if needed) ────────────────

export const analyzeWithJdText = async (jdText: string, resumeSkills: ResumeSkills): Promise<AnalyzeResponse> => {
  return request<AnalyzeResponse>(API_ROUTES.analyzeText, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      jd_text: jdText,
      inference: DEFAULT_INFERENCE,
      resume_skills: resumeSkills,
    }),
  });
};

export const analyzeWithJdFile = async (file: File, resumeSkills: ResumeSkills): Promise<AnalyzeResponse> => {
  const formData = new FormData();
  formData.append("file", file);
  formData.append("inference", DEFAULT_INFERENCE);
  formData.append("resume_skills", JSON.stringify(resumeSkills));

  return request<AnalyzeResponse>(API_ROUTES.analyzePdf, {
    method: "POST",
    body: formData,
  });
};